//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWACSTicketLibrary
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ticket
    {
        public int Id { get; set; }

        [Display(Name = "Ticket ID")]
        public string TicketId { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Solution { get; set; }

        [Display(Name = "Date observed")]
        public System.DateTime DateObserved { get; set; }

        [Display(Name = "Planned end date")]
        public System.DateTime PlannedEndDate { get; set; }
        public string Progress { get; set; }
        public string Status { get; set; }
        public int CreatorId { get; set; }
        public int ResponsibleId { get; set; }
    
        public virtual Worker Creator { get; set; }
        public virtual Worker Responsible { get; set; }
    }
}
