//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWACSTicketSystemLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public string TicketId { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Solution { get; set; }
        public string DateObserved { get; set; }
        public string PlannedEndDate { get; set; }
        public string Progress { get; set; }
        public string Status { get; set; }
        public int ResponsibleId { get; set; }
        public int CreatedId { get; set; }
    
        public virtual User ResponsibleFor { get; set; }
        public virtual User IsCreated { get; set; }
    }
}
